In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../input/mlbplaybyplay2010s/all2010.csv')
data = data[data['BAT_EVENT_FL'] == 'T'].reset_index(drop=True)
data.head()

GAME_ID AWAY_TEAM_ID  INN_CT  BAT_HOME_ID  OUTS_CT  BALLS_CT  \
0  ANA201004050          MIN       1            0        0         2   
1  ANA201004050          MIN       1            0        1         0   
2  ANA201004050          MIN       1            0        2         1   
3  ANA201004050          MIN       1            1        0         3   
4  ANA201004050          MIN       1            1        0         0   

   STRIKES_CT PITCH_SEQ_TX  AWAY_SCORE_CT  HOME_SCORE_CT  ...  \
0           2     CSBFFBFC              0              0  ...   
1           1           FX              0              0  ...   
2           1          CBX              0              0  ...   
3           2   BBCCFBFFFB              0              0  ...   
4           1           CX              0              0  ...   

  REMOVED_FOR_PH_BAT_FLD_CD PO1_FLD_CD PO2_FLD_CD PO3_FLD_CD ASS1_FLD_CD  \
0                         0          2          0          0           0   
1                         0          3          0          0           4   
2                         0          3          0          0           4   
3                         0          0          0          0           0   
4                         0          8          0          0           0   

  ASS2_FLD_CD ASS3_FLD_CD ASS4_FLD_CD ASS5_FLD_CD EVENT_ID  
0           0           0           0           0        1  
1           0           0           0           0        2  
2           0           0           0           0        3  
3           0           0           0           0        4  
4           0           0           0           0        5  

[5 rows x 97 columns]

In [7]:
preprocessed = pd.read_csv('../input/preprocessed/all2010.csv')
preprocessed.head()

AWAY_TEAM_ID  HOME_TEAM_ID  GAME_END_FL  AWAY_START_PIT_ID  \
0            16             0        False                605   
1            16             0        False                605   
2            16             0        False                605   
3            16             0        False                605   
4            16             0        False                605   

   HOME_START_PIT_ID  INN_END_FL  AWAY_START_BAT1_ID  AWAY_START_BAT2_ID  \
0                 21        True                 809                 393   
1                 21        True                 809                 393   
2                 21        True                 809                 393   
3                 21        True                 809                 393   
4                 21        True                 809                 393   

   AWAY_START_BAT3_ID  AWAY_START_BAT4_ID  ...  END_INN_CT  END_BAT_HOME_ID  \
0                 546                 600  ...           1                0   
1                 546                 600  ...           1                0   
2                 546                 600  ...           1                1   
3                 546                 600  ...           1                1   
4                 546                 600  ...           1                1   

   END_OUTS_CT  END_BASE1_RUN_ID  END_BASE2_RUN_ID  END_BASE3_RUN_ID  \
0            1                 0                 0                 0   
1            2                 0                 0                 0   
2            0                 0                 0                 0   
3            0                26                 0                 0   
4            1                 0                26                 0   

   END_BAT_LINEUP_ID  END_PIT_LINEUP_ID  END_AWAY_SCORE_CT  END_HOME_SCORE_CT  
0                  2                  0                  0                  0  
1                  3                  0                  0                  0  
2                  1                  0                  0                  0  
3                  2                  0                  0                  0  
4                  3                  0                  0                  0  

[5 rows x 44 columns]

In [8]:
preprocessed.columns

Index(['AWAY_TEAM_ID', 'HOME_TEAM_ID', 'GAME_END_FL', 'AWAY_START_PIT_ID',
       'HOME_START_PIT_ID', 'INN_END_FL', 'AWAY_START_BAT1_ID',
       'AWAY_START_BAT2_ID', 'AWAY_START_BAT3_ID', 'AWAY_START_BAT4_ID',
       'AWAY_START_BAT5_ID', 'AWAY_START_BAT6_ID', 'AWAY_START_BAT7_ID',
       'AWAY_START_BAT8_ID', 'AWAY_START_BAT9_ID', 'HOME_START_BAT1_ID',
       'HOME_START_BAT2_ID', 'HOME_START_BAT3_ID', 'HOME_START_BAT4_ID',
       'HOME_START_BAT5_ID', 'HOME_START_BAT6_ID', 'HOME_START_BAT7_ID',
       'HOME_START_BAT8_ID', 'HOME_START_BAT9_ID', 'INN_CT', 'BAT_HOME_ID',
       'OUTS_CT', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID',
       'BAT_LINEUP_ID', 'PIT_LINEUP_ID', 'AWAY_SCORE_CT', 'HOME_SCORE_CT',
       'END_INN_CT', 'END_BAT_HOME_ID', 'END_OUTS_CT', 'END_BASE1_RUN_ID',
       'END_BASE2_RUN_ID', 'END_BASE3_RUN_ID', 'END_BAT_LINEUP_ID',
       'END_PIT_LINEUP_ID', 'END_AWAY_SCORE_CT', 'END_HOME_SCORE_CT'],
      dtype='object')

In [3]:
d = data.iloc[[0]]
d

GAME_ID AWAY_TEAM_ID  INN_CT  BAT_HOME_ID  OUTS_CT  BALLS_CT  \
0  ANA201004050          MIN       1            0        0         2   

   STRIKES_CT PITCH_SEQ_TX  AWAY_SCORE_CT  HOME_SCORE_CT  ...  \
0           2     CSBFFBFC              0              0  ...   

  REMOVED_FOR_PH_BAT_FLD_CD PO1_FLD_CD PO2_FLD_CD PO3_FLD_CD ASS1_FLD_CD  \
0                         0          2          0          0           0   

  ASS2_FLD_CD ASS3_FLD_CD ASS4_FLD_CD ASS5_FLD_CD EVENT_ID  
0           0           0           0           0        1  

[1 rows x 97 columns]

In [5]:
d['INN_CT'].where(d['BAT_HOME_ID'] == 1, d['OUTS_CT']).values

array([0])

In [7]:
len(list(data['BAT_ID'].unique()) + list(data['BASE1_RUN_ID'].unique()) + list(data['BASE2_RUN_ID'].unique()) + list(data['BASE3_RUN_ID'].unique()))

3170

In [46]:
data[['BAT_ID', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID']].head(20)

BAT_ID BASE1_RUN_ID BASE2_RUN_ID BASE3_RUN_ID
0   spand001          NaN          NaN          NaN
1   hudso001          NaN          NaN          NaN
2   mauej001          NaN          NaN          NaN
3   aybae001          NaN          NaN          NaN
4   abreb001     aybae001          NaN          NaN
5   huntt001          NaN     aybae001          NaN
6   matsh001     huntt001     aybae001          NaN
7   morak001     huntt001     aybae001          NaN
8   rivej001     morak001     huntt001          NaN
9   kendh001     rivej001     morak001          NaN
10  mornj001          NaN          NaN          NaN
11  cuddm001     mornj001          NaN          NaN
12  kubej002     mornj001          NaN          NaN
13  yound003     mornj001          NaN          NaN
14  hardj003          NaN          NaN          NaN
15  woodb003          NaN          NaN          NaN
16  mathj001          NaN          NaN          NaN
17  aybae001          NaN          NaN          NaN
18  abreb001          NaN          NaN          NaN
19  puntn001          NaN          NaN          NaN

In [47]:
import numpy as np
data[['BAT_ID', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID']] = \
    data[['BAT_ID', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID']].fillna('')
categories = np.unique(data[['BAT_ID', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID']].values.reshape(-1)).reshape(1, -1)

In [40]:
# categories

In [48]:
from sklearn.preprocessing import OrdinalEncoder

bat_encoder = OrdinalEncoder()
bat_encoder.categories_ = categories

data['BAT_ID'] = bat_encoder.transform(data['BAT_ID'].values.reshape(-1, 1)).squeeze()
data['BASE1_RUN_ID'] = bat_encoder.transform(data['BASE1_RUN_ID'].values.reshape(-1, 1)).squeeze()
data['BASE2_RUN_ID'] = bat_encoder.transform(data['BASE2_RUN_ID'].values.reshape(-1, 1)).squeeze()
data['BASE3_RUN_ID'] = bat_encoder.transform(data['BASE3_RUN_ID'].values.reshape(-1, 1)).squeeze()

data[['BAT_ID', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID']].head(20)

BAT_ID  BASE1_RUN_ID  BASE2_RUN_ID  BASE3_RUN_ID
0    809.0           0.0           0.0           0.0
1    393.0           0.0           0.0           0.0
2    546.0           0.0           0.0           0.0
3     26.0           0.0           0.0           0.0
4      2.0          26.0           0.0           0.0
5    402.0           0.0          26.0           0.0
6    542.0         402.0          26.0           0.0
7    595.0         402.0          26.0           0.0
8    725.0         595.0         402.0           0.0
9    448.0         725.0         595.0           0.0
10   600.0           0.0           0.0           0.0
11   191.0         600.0           0.0           0.0
12   463.0         600.0           0.0           0.0
13   934.0         600.0           0.0           0.0
14   348.0           0.0           0.0           0.0
15   924.0           0.0           0.0           0.0
16   539.0           0.0           0.0           0.0
17    26.0           0.0           0.0           0.0
18     2.0           0.0           0.0           0.0
19   693.0           0.0           0.0           0.0

In [13]:
data.columns

Index(['GAME_ID', 'AWAY_TEAM_ID', 'INN_CT', 'BAT_HOME_ID', 'OUTS_CT',
       'BALLS_CT', 'STRIKES_CT', 'PITCH_SEQ_TX', 'AWAY_SCORE_CT',
       'HOME_SCORE_CT', 'BAT_ID', 'BAT_HAND_CD', 'RESP_BAT_ID',
       'RESP_BAT_HAND_CD', 'PIT_ID', 'PIT_HAND_CD', 'RESP_PIT_ID',
       'RESP_PIT_HAND_CD', 'POS2_FLD_ID', 'POS3_FLD_ID', 'POS4_FLD_ID',
       'POS5_FLD_ID', 'POS6_FLD_ID', 'POS7_FLD_ID', 'POS8_FLD_ID',
       'POS9_FLD_ID', 'BASE1_RUN_ID', 'BASE2_RUN_ID', 'BASE3_RUN_ID',
       'EVENT_TX', 'LEADOFF_FL', 'PH_FL', 'BAT_FLD_CD', 'BAT_LINEUP_ID',
       'EVENT_CD', 'BAT_EVENT_FL', 'AB_FL', 'H_FL', 'SH_FL', 'SF_FL',
       'EVENT_OUTS_CT', 'DP_FL', 'TP_FL', 'RBI_CT', 'WP_FL', 'PB_FL', 'FLD_CD',
       'BATTEDBALL_CD', 'BUNT_FL', 'FOUL_FL', 'BATTEDBALL_LOC_TX', 'ERR_CT',
       'ERR1_FLD_CD', 'ERR1_CD', 'ERR2_FLD_CD', 'ERR2_CD', 'ERR3_FLD_CD',
       'ERR3_CD', 'BAT_DEST_ID', 'RUN1_DEST_ID', 'RUN2_DEST_ID',
       'RUN3_DEST_ID', 'BAT_PLAY_TX', 'RUN1_PLAY_TX', 'RUN2_PLAY_TX',
       'RUN3_PL

In [14]:
dict(enumerate(data.AWAY_TEAM_ID.unique()))

{0: 'MIN',
 1: 'OAK',
 2: 'DET',
 3: 'NYA',
 4: 'CLE',
 5: 'TBA',
 6: 'TOR',
 7: 'SEA',
 8: 'MIL',
 9: 'LAN',
 10: 'COL',
 11: 'TEX',
 12: 'KCA',
 13: 'BOS',
 14: 'BAL',
 15: 'CHA',
 16: 'SDN',
 17: 'PIT',
 18: 'SLN',
 19: 'PHI',
 20: 'SFN',
 21: 'ATL',
 22: 'CHN',
 23: 'FLO',
 24: 'NYN',
 25: 'WAS',
 26: 'CIN',
 27: 'HOU',
 28: 'ARI',
 29: 'ANA'}

In [15]:
games = {game_id: df for game_id, df in data.groupby(data['GAME_ID'])}

In [16]:
len(games.keys())

2430

In [17]:
keys = list(games.keys())

In [18]:
first_game = keys[1]
first_game

'ANA201004060'

In [19]:
first_game_df = games[first_game]
first_game_df

GAME_ID AWAY_TEAM_ID  INN_CT  BAT_HOME_ID  OUTS_CT  BALLS_CT  \
73   ANA201004060          MIN       1            0        0         3   
74   ANA201004060          MIN       1            0        0         0   
75   ANA201004060          MIN       1            0        1         1   
76   ANA201004060          MIN       1            0        1         1   
77   ANA201004060          MIN       1            0        1         0   
..            ...          ...     ...          ...      ...       ...   
143  ANA201004060          MIN       9            0        1         1   
144  ANA201004060          MIN       9            0        2         2   
145  ANA201004060          MIN       9            1        0         0   
146  ANA201004060          MIN       9            1        1         3   
147  ANA201004060          MIN       9            1        2         2   

     STRIKES_CT PITCH_SEQ_TX  AWAY_SCORE_CT  HOME_SCORE_CT  ...  \
73            1        BBBCB              0              0  ...   
74            0            X              0              0  ...   
75            1          BCX              0              0  ...   
76            2         CFBX              2              0  ...   
77            1           CX              2              0  ...   
..          ...          ...            ...            ...  ...   
143           0           BX              5              3  ...   
144           2        CBCBX              5              3  ...   
145           2         .CFS              5              3  ...   
146           2     .BCFFBBX              5              3  ...   
147           2       CBCFBC              5              3  ...   

    REMOVED_FOR_PH_BAT_FLD_CD PO1_FLD_CD PO2_FLD_CD PO3_FLD_CD ASS1_FLD_CD  \
73                          0          0          0          0           0   
74                          0          6          0          0           3   
75                          0          0          0          0           0   
76                          0          0          0          0           0   
77                          0          0          0          0           0   
..                        ...        ...        ...        ...         ...   
143                         0          3          0          0           1   
144                         0          3          0          0           4   
145                         0          2          0          0           0   
146                         2          5          0          0           0   
147                         0          2          0          0           0   

    ASS2_FLD_CD ASS3_FLD_CD ASS4_FLD_CD ASS5_FLD_CD EVENT_ID  
73            0           0           0           0        1  
74            0           0           0           0        2  
75            0           0           0           0        3  
76            0           0           0           0        4  
77            0           0           0           0        5  
..          ...         ...         ...         ...      ...  
143           0           0           0           0       72  
144           0           0           0           0       73  
145           0           0           0           0       74  
146           0           0           0           0       75  
147           0           0           0           0       76  

[75 rows x 97 columns]

In [22]:
first_game_df[first_game_df['BAT_HOME_ID'] == 0]['BAT_ID'][:9]


73    spand001
74    hudso001
75    mauej001
76    mornj001
77    cuddm001
78    kubej002
79    yound003
80    hardj003
85    puntn001
Name: BAT_ID, dtype: object

In [21]:
first_game_df[first_game_df['BAT_HOME_ID'] == 1]['BAT_ID']

81     aybae001
82     abreb001
83     huntt001
84     matsh001
89     morak001
90     rivej001
91     kendh001
92     woodb003
97     mathj001
98     aybae001
99     abreb001
100    huntt001
101    matsh001
106    morak001
107    rivej001
108    kendh001
109    woodb003
110    mathj001
115    aybae001
116    abreb001
117    huntt001
118    matsh001
119    morak001
120    rivej001
126    kendh001
127    woodb003
128    mathj001
132    aybae001
133    abreb001
134    huntt001
135    matsh001
139    morak001
140    rivej001
141    kendh001
145    woodb003
146    iztum001
147    aybae001
Name: BAT_ID, dtype: object

In [23]:
d = {1: 2, 3: 4}
d.values()

dict_values([2, 4])

In [24]:
data

GAME_ID AWAY_TEAM_ID  INN_CT  BAT_HOME_ID  OUTS_CT  BALLS_CT  \
0       ANA201004050          MIN       1            0        0         2   
1       ANA201004050          MIN       1            0        1         0   
2       ANA201004050          MIN       1            0        2         1   
3       ANA201004050          MIN       1            1        0         3   
4       ANA201004050          MIN       1            1        0         0   
...              ...          ...     ...          ...      ...       ...   
185548  WAS201009290          PHI       9            0        1         1   
185549  WAS201009290          PHI       9            0        2         1   
185550  WAS201009290          PHI       9            1        0         2   
185551  WAS201009290          PHI       9            1        1         0   
185552  WAS201009290          PHI       9            1        2         2   

        STRIKES_CT PITCH_SEQ_TX  AWAY_SCORE_CT  HOME_SCORE_CT  ...  \
0                2     CSBFFBFC              0              0  ...   
1                1           FX              0              0  ...   
2                1          CBX              0              0  ...   
3                2   BBCCFBFFFB              0              0  ...   
4                1           CX              0              0  ...   
...            ...          ...            ...            ...  ...   
185548           2         CSBC              7              1  ...   
185549           2        .CCBX              7              1  ...   
185550           2       .SBSBS              7              1  ...   
185551           2          FCX              7              1  ...   
185552           2        BCBCX              7              1  ...   

       REMOVED_FOR_PH_BAT_FLD_CD PO1_FLD_CD PO2_FLD_CD PO3_FLD_CD ASS1_FLD_CD  \
0                              0          2          0          0           0   
1                              0          3          0          0           4   
2                              0          3          0          0           4   
3                              0          0          0          0           0   
4                              0          8          0          0           0   
...                          ...        ...        ...        ...         ...   
185548                         0          2          0          0           0   
185549                         1          3          0          0           5   
185550                         0          2          0          0           0   
185551                         0          9          0          0           0   
185552                         0          8          0          0           0   

       ASS2_FLD_CD ASS3_FLD_CD ASS4_FLD_CD ASS5_FLD_CD EVENT_ID  
0                0           0           0           0        1  
1                0           0           0           0        2  
2                0           0           0           0        3  
3                0           0           0           0        4  
4                0           0           0           0        5  
...            ...         ...         ...         ...      ...  
185548           0           0           0           0       65  
185549           0           0           0           0       66  
185550           0           0           0           0       67  
185551           0           0           0           0       68  
185552           0           0           0           0       69  

[185553 rows x 97 columns]

In [26]:
%timeit data[['INN_CT', 'BAT_HOME_ID']]

654 µs ± 4.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
%timeit data.loc[:, ['INN_CT', 'BAT_HOME_ID']]

641 µs ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
%timeit data.iloc[[1, 2, 3]]

149 µs ± 815 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [29]:
data.iloc[[1, 2, 3]]

GAME_ID AWAY_TEAM_ID  INN_CT  BAT_HOME_ID  OUTS_CT  BALLS_CT  \
1  ANA201004050          MIN       1            0        1         0   
2  ANA201004050          MIN       1            0        2         1   
3  ANA201004050          MIN       1            1        0         3   

   STRIKES_CT PITCH_SEQ_TX  AWAY_SCORE_CT  HOME_SCORE_CT  ...  \
1           1           FX              0              0  ...   
2           1          CBX              0              0  ...   
3           2   BBCCFBFFFB              0              0  ...   

  REMOVED_FOR_PH_BAT_FLD_CD PO1_FLD_CD PO2_FLD_CD PO3_FLD_CD ASS1_FLD_CD  \
1                         0          3          0          0           4   
2                         0          3          0          0           4   
3                         0          0          0          0           0   

  ASS2_FLD_CD ASS3_FLD_CD ASS4_FLD_CD ASS5_FLD_CD EVENT_ID  
1           0           0           0           0        2  
2           0           0           0           0        3  
3           0           0           0           0        4  

[3 rows x 97 columns]

In [30]:
data[['INN_CT', 'BAT_HOME_ID']].iloc[[1, 2, 3]]

INN_CT  BAT_HOME_ID
1       1            0
2       1            0
3       1            1

In [31]:
data[['INN_CT', 'BAT_HOME_ID']].iloc[[1, 2, 3]].values

array([[1, 0],
       [1, 0],
       [1, 1]])

In [49]:
data

GAME_ID AWAY_TEAM_ID  INN_CT  BAT_HOME_ID  OUTS_CT  BALLS_CT  \
0       ANA201004050          MIN       1            0        0         2   
1       ANA201004050          MIN       1            0        1         0   
2       ANA201004050          MIN       1            0        2         1   
3       ANA201004050          MIN       1            1        0         3   
4       ANA201004050          MIN       1            1        0         0   
...              ...          ...     ...          ...      ...       ...   
185548  WAS201009290          PHI       9            0        1         1   
185549  WAS201009290          PHI       9            0        2         1   
185550  WAS201009290          PHI       9            1        0         2   
185551  WAS201009290          PHI       9            1        1         0   
185552  WAS201009290          PHI       9            1        2         2   

        STRIKES_CT PITCH_SEQ_TX  AWAY_SCORE_CT  HOME_SCORE_CT  ...  \
0                2     CSBFFBFC              0              0  ...   
1                1           FX              0              0  ...   
2                1          CBX              0              0  ...   
3                2   BBCCFBFFFB              0              0  ...   
4                1           CX              0              0  ...   
...            ...          ...            ...            ...  ...   
185548           2         CSBC              7              1  ...   
185549           2        .CCBX              7              1  ...   
185550           2       .SBSBS              7              1  ...   
185551           2          FCX              7              1  ...   
185552           2        BCBCX              7              1  ...   

        REMOVED_FOR_PH_BAT_FLD_CD PO1_FLD_CD PO2_FLD_CD PO3_FLD_CD  \
0                               0          2          0          0   
1                               0          3          0          0   
2                               0          3          0          0   
3                               0          0          0          0   
4                               0          8          0          0   
...                           ...        ...        ...        ...   
185548                          0          2          0          0   
185549                          1          3          0          0   
185550                          0          2          0          0   
185551                          0          9          0          0   
185552                          0          8          0          0   

       ASS1_FLD_CD ASS2_FLD_CD ASS3_FLD_CD ASS4_FLD_CD ASS5_FLD_CD EVENT_ID  
0                0           0           0           0           0        1  
1                4           0           0           0           0        2  
2                4           0           0           0           0        3  
3                0           0           0           0           0        4  
4                0           0           0           0           0        5  
...            ...         ...         ...         ...         ...      ...  
185548           0           0           0           0           0       65  
185549           5           0           0           0           0       66  
185550           0           0           0           0           0       67  
185551           0           0           0           0           0       68  
185552           0           0           0           0           0       69  

[185553 rows x 97 columns]

In [50]:
%timeit data.iloc[[1, 2, 3, 4, 5]][['AWAY_TEAM_ID', 'INN_CT']]

604 µs ± 2.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [52]:
%timeit data.loc[[1, 2, 3, 4, 5]][['AWAY_TEAM_ID', 'INN_CT']]

671 µs ± 2.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [51]:
%timeit data[['AWAY_TEAM_ID', 'INN_CT']].iloc[[1, 2, 3, 4, 5]]

1.83 ms ± 6.86 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
nt = {'inn_ct': 1, 'bat_home_id': 2}
nt.values()

dict_values([1, 2])

In [1]:
import torch
torch.__version__

'1.7.0'

In [2]:
a = torch.randn(4, 9)
a

tensor([[ 1.4441,  0.4601, -0.2286, -0.8168,  0.5527, -2.2353,  0.1349, -1.2824,
         -0.5266],
        [ 0.0048, -2.1113, -0.7291,  1.6114,  1.5514,  0.9058, -0.7789, -0.7269,
          1.0731],
        [ 0.1919, -0.9282,  0.0795,  1.8194,  0.1821,  0.5131,  0.2190,  1.1736,
          0.0864],
        [ 1.1096,  0.1664,  0.1047, -1.2285, -1.6095, -0.5774, -1.3301,  0.7788,
          0.1295]])

In [40]:
b = torch.randint(1, 10, size=(4, ))
b

tensor([8, 1, 1, 4])

In [50]:
i = 9
torch.eye(9)[(b - 1 + i) % 9]

tensor([[0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [57]:
torch.eye(9)[[1, 2]]


tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [80]:
torch.eye(9).unsqueeze(0).repeat(2, 1, 1)[:, b]

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0.]]])

In [82]:
bats = torch.randint(1, 100, size=(4, 9))
bats

tensor([[81, 20, 69, 55, 50, 98, 71, 17, 15],
        [18, 98, 13, 18, 86, 34, 26, 16, 68],
        [39, 28, 59, 76, 23, 59,  2, 22, 44],
        [60, 11, 55, 44, 51, 84, 25, 88, 53]])

In [112]:
bats.gather(0, torch.tensor([[1, 0], [2, 3]]))

tensor([[18, 20],
        [39, 11]])

In [90]:
torch.gather(bats, 1, torch.tensor([[0, 1], [2, 3]]))

tensor([[81, 20],
        [13, 18]])

In [92]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
b

tensor([8, 1, 1, 4])

In [103]:
b = b.unsqueeze(1)
b

tensor([[8],
        [1],
        [1],
        [4]])

In [105]:
bb = torch.cat([b, (b + 1) % 9], 1)
bb

tensor([[8, 0],
        [1, 2],
        [1, 2],
        [4, 5]])

In [106]:
i = 0
torch.gather(bats, 1, bb)

tensor([[15, 81],
        [98, 13],
        [28, 59],
        [51, 84]])