In [18]:
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from model import Model

In [6]:
BATCH_SIZE = 4

In [10]:
a = torch.randint(3, (BATCH_SIZE, 1))
a

tensor([[1],
        [2],
        [2],
        [1]])

In [12]:
F.one_hot(a.squeeze())

tensor([[0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]])

In [13]:
b = torch.randn(BATCH_SIZE, 4)
b

tensor([[-0.6685, -0.4357, -0.3300, -0.8522],
        [-0.5419, -0.7764, -0.2171, -0.9865],
        [-0.4180,  0.5285, -0.0835,  0.2179],
        [-0.6201, -2.1441, -0.1519, -0.0270]])

In [22]:
softmax = nn.Softmax()
softmax(b)

tensor([[0.2224, 0.2807, 0.3119, 0.1850],
        [0.2621, 0.2073, 0.3626, 0.1680],
        [0.1457, 0.3755, 0.2036, 0.2752],
        [0.2162, 0.0471, 0.3453, 0.3913]])

In [29]:
clip = lambda x: x.where(x <= 0, torch.Tensor([1]))
clip(b)

tensor([[-0.6685, -0.4357, -0.3300, -0.8522],
        [-0.5419, -0.7764, -0.2171, -0.9865],
        [-0.4180,  1.0000, -0.0835,  1.0000],
        [-0.6201, -2.1441, -0.1519, -0.0270]])