In [1]:
import torch

In [5]:
a = torch.rand(2, 5)
a

tensor([[0.2414, 0.1427, 0.8627, 0.7543, 0.8381],
        [0.8474, 0.4453, 0.6014, 0.6448, 0.5221]])

In [6]:
b = torch.Tensor([1., 0., 0., 1., 1.])
b

tensor([1., 0., 0., 1., 1.])

In [7]:
a * b

tensor([[0.2414, 0.0000, 0.0000, 0.7543, 0.8381],
        [0.8474, 0.0000, 0.0000, 0.6448, 0.5221]])